### ISSUE TITLE
google cloud storage

### ISSUE THREAD

**Issue by calvinmetcalf** [connormanning/arbiter#13]
now this should theoretically be easy on the grounds that it has a [compatibility api](https://cloud.google.com/storage/docs/migrating#migration-simple) so the google one could be identical to the amazon one just with the endpoint updated, in practice code like [this](https://github.com/connormanning/arbiter/blob/55d44ac2a3b4dafe2ae319070603a7c6d489a6f1/arbiter/drivers/s3.cpp#L46-L48) makes me suspect that it might not be so simple.

**Comment by msmitherdc** [comment]
@calvinmetcalf that code is just there to support authentication via instance profiles. Its just one of many auth methods in arbiter.

**Comment by calvinmetcalf** [comment]
ok so is the endpoint configurable curently ?

**Comment by msmitherdc** [comment]
Yes, via config file or env value

**Comment by calvinmetcalf** [comment]
is there any documentation on the config options?

**Comment by connormanning** [comment]
Config settings follow [awscli](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence).  You would want to create an S3 driver with something like this:
```
{ "access": "my-access-key",
  "secret": "my-secret-key",
  "endpoint": "google-cloud-endpoint" }
```

I suppose you'd want to scrape up those Google Cloud credentials from the filesystem or environment or however is typical for Google Cloud within your Driver.  Then you'd privately instantiate an S3 driver with the above and defer Google Cloud requests to it.

**Comment by calvinmetcalf** [comment]
ah thanks, closing this in favor of connormanning/entwine#34 as it seems its theoretically possible to do this, assuming I configure it right
