### ISSUE TITLE
Arbiter Ctor Does Too Much

### ISSUE THREAD

**Issue by abellgithub** [connormanning/arbiter#36]
There are lots of side-effects when creating an Arbiter object.  A simple construction of an arbiter object should do little to nothing.  One should be able to find out if arbiter supports various files, for example, without creating a thread pool or attempting to create various drivers.

**Comment by connormanning** [comment]
Done in bd3692efa9b94cf6257bec9aab81cc78ff175ff2.  Drivers are now waken up on-demand only when accessed and the driver map has a lock around it.
