### ISSUE TITLE
add AWS_ENDPOINT_URL environment support

### ISSUE THREAD

**Issue by msmitherdc** [connormanning/arbiter#50]
in some cases, the s3 endpoint from the endpoint url goes through really slow pipes at NGA but pointing to the cloudfront url is significantly faster. By setting a custom AWS_ENDPOINT_URL environment variable, we can route the s3 calls to the cloudfront url without affecting the general endpoints and while still using s3 for lists

**Comment by hobu** [comment]
Turns out we want to have this before the PDAL 2.7 release, which is expected in the next week or two.
